# docker-compose.yml
version: '3.8'

services:
  crawler:
    build: .
    environment:
      - CRAWLER_CONFIG=/app/config/crawler_config.yml
    volumes:
      - ./config:/app/config
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
